version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
    links:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo/db

  ms-cooperativismo-pauta:
    container_name: ms-cooperativismo-pauta
    image: ms-cooperativismo-pauta:0.0.1
    ports:
     - "8090:8090"
    links:
      - mongo
  
  ms-cooperativismo-session:
    image: ms-cooperativismo-sessao:0.0.1
    ports:
      - "8091:8091"
    links:
      - mongo
  
  ms-cooperativismo-votos:
    image: ms-cooperativismo-votos:0.0.1
    ports:
      - "8092:8092"
    links:
      - mongo
      - kafka
  
  ms-cooperativismo-event:
    image: ms-cooperativismo-event:0.0.1
    environment:
      MONGODB_DATABASE: db
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      KAFKA_SERVER: localhost:9092
    ports:
      - "8093:8093"
    links:
      - mongo
      - kafka

  ms-cooperativismo-relatorio:
    image: ms-cooperativismo-relatorio:0.0.1
    ports:
      - "8094:8094"
    links:
      - mongo 

networks:
  broker-kafka:
  mongo-compose-network:
    driver: bridge
